import { useEffect, useState } from "react";
import "./App.css";
import { SYSTEMS, createEmployee, loadData, saveData } from "./data/dataStore";

const FLOW = ["Exit event", "Access discovery", "Revocation", "Verification", "Escalation", "Audit report"];
const navItems = [["Overview", "⌂"], ["Employees", "♙"], ["Agent Activity", "◉"], ["Access Control", "▣"], ["Audit Reports", "▤"], ["How it works", "?"]];

function App() {
  const [page, setPage] = useState("Overview");
  const [data, setData] = useState(loadData);
  const [workflow, setWorkflow] = useState(null);
  const [showAdd, setShowAdd] = useState(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [form, setForm] = useState({ name: "", employeeId: "", email: "", role: "", department: "", exitDate: "" });
  const employees = data.employees;
  const selected = employees.find((employee) => employee.id === workflow?.employeeId);
  const activeCases = employees.filter((employee) => employee.status === "In Progress").length;
  const completedCases = employees.filter((employee) => employee.status === "Completed").length;
  const exceptions = employees.filter((employee) => employee.exception).length;

  useEffect(() => saveData(data), [data]);

  const addActivity = (type, text, employeeId = workflow?.employeeId) => {
    setData((current) => ({ ...current, activities: [{ id: Date.now() + Math.random(), type, text, time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" }), employeeId }, ...current.activities].slice(0, 100) }));
  };
  const updateEmployee = (id, changes) => setData((current) => ({ ...current, employees: current.employees.map((item) => item.id === id ? { ...item, ...changes } : item) }));

  function runWorkflowStep() {
    if (!workflow || !selected) return;
    const phase = workflow.phase;
    if (phase === 0) { addActivity("DISCOVERY", `Access inventory found in ${SYSTEMS.length} connected systems`); updateEmployee(selected.id, { phase: 1, systems: SYSTEMS.map((system) => ({ ...system, status: "Active", attempts: 0 })) }); }
    if (phase === 1) { addActivity("REVOCATION", "Revocation tasks created for all discovered access"); updateEmployee(selected.id, { phase: 2 }); }
    if (phase === 2) { addActivity("ACCESS", "Revocation requested across all six connected systems"); updateEmployee(selected.id, { phase: 3, systems: selected.systems.map((system) => ({ ...system, status: system.name === "AWS" ? "Revocation requested" : "Revoked", attempts: 1 })) }); }
    if (phase === 3) { addActivity("VERIFY", "Verification passed for 5 systems; AWS access is still active"); updateEmployee(selected.id, { phase: 4, systems: selected.systems.map((system) => ({ ...system, status: system.name === "AWS" ? "Active" : "Revoked" })) }); }
    if (phase === 4) { addActivity("ESCALATE", "AWS verification failed twice. IT Security escalation created"); const finished = { ...selected, phase: 5, status: "Completed", exception: true, systems: selected.systems.map((system) => ({ ...system, status: system.name === "AWS" ? "Escalated" : "Revoked", attempts: system.name === "AWS" ? 2 : system.attempts })) }; const report = { id: `RPT-${Date.now()}`, employeeId: selected.id, employee: finished, createdAt: new Date().toLocaleString(), systemsChecked: 6, revoked: 5, escalated: 1 }; setData((current) => ({ ...current, employees: current.employees.map((item) => item.id === selected.id ? finished : item), reports: [report, ...current.reports] })); addActivity("AUDIT", "Audit report generated and stored", selected.id); }
    setWorkflow((current) => current ? { ...current, phase: Math.min(current.phase + 1, 5) } : current);
  }

  useEffect(() => {
    if (!workflow || workflow.phase >= 5 || !selected) return undefined;
    const timer = setTimeout(runWorkflowStep, 850);
    return () => clearTimeout(timer);
  }, [workflow, selected, runWorkflowStep]);

  const addEmployee = (event) => {
    event.preventDefault();
    if (Object.values(form).some((value) => !value)) return;
    setData((current) => ({ ...current, employees: [createEmployee(form), ...current.employees] }));
    setForm({ name: "", employeeId: "", email: "", role: "", department: "", exitDate: "" });
    setShowAdd(false);
  };
  const startOffboarding = (employee) => { setWorkflow({ employeeId: employee.id, phase: 0 }); updateEmployee(employee.id, { status: "In Progress", phase: 0, systems: [] }); addActivity("EVENT", `Exit event received for ${employee.name}`, employee.id); };
  const resetDemo = () => { if (!window.confirm("Reset all local demo data?")) return; localStorage.removeItem("offboardData"); setData(loadData(true)); setWorkflow(null); setPage("Overview"); };

  return <div className="app">
    <aside className={`sidebar ${mobileMenuOpen ? "mobile-open" : ""}`}>
      <div className="brand"><div className="brand-mark">O</div><div><strong>OffboardAI</strong><span>Security command center</span></div></div>
      <p className="side-label">OPERATIONS</p>
      <nav>{navItems.map(([name, icon]) => <button key={name} className={page === name ? "nav-item active" : "nav-item"} onClick={() => { setPage(name); setMobileMenuOpen(false); }}><i>{icon}</i>{name}</button>)}</nav>
      <div className="sidebar-bottom"><div className="agent-online"><span /> <div><strong>Agent online</strong><small>6 adapters connected</small></div></div><button className="reset-btn" onClick={resetDemo}>Reset local data</button></div>
    </aside>
    <main className="main">
      <header className="topbar"><button className="mobile-menu-btn" onClick={() => setMobileMenuOpen(!mobileMenuOpen)}>{mobileMenuOpen ? "×" : "☰"}</button><span className="crumb">SECURITY / {page.toUpperCase()}</span><div className="top-actions"><span className="live"><b /> LIVE</span><button className="add-btn" onClick={() => setShowAdd(true)}>+ Add employee</button></div></header>
      {page === "Overview" && <Overview employees={employees} activeCases={activeCases} completedCases={completedCases} exceptions={exceptions} onAdd={() => setShowAdd(true)} onStart={startOffboarding} onActivity={() => setPage("Agent Activity")} />}
      {page === "Employees" && <Employees employees={employees} onAdd={() => setShowAdd(true)} onStart={startOffboarding} />}
      {page === "Agent Activity" && <Activity activities={data.activities} />}
      {page === "Access Control" && <AccessControl onAdd={() => setShowAdd(true)} />}
      {page === "Audit Reports" && <Reports reports={data.reports} />}
      {page === "How it works" && <HowItWorks />}
    </main>
    {showAdd && <AddModal form={form} setForm={setForm} onClose={() => setShowAdd(false)} onSubmit={addEmployee} />}
    {selected && workflow && <WorkflowModal employee={selected} phase={workflow.phase} onClose={() => setWorkflow(null)} onOpenReport={() => { setWorkflow(null); setPage("Audit Reports"); }} />}
  </div>;
}

function Overview({ employees, activeCases, completedCases, exceptions, onAdd, onStart, onActivity }) { return <><section className="hero"><div><span className="eyebrow">● AUTONOMOUS SECURITY AGENT</span><h1>Employee offboarding,<br /><em>verified.</em></h1><p>Discover, revoke and verify access across enterprise applications with an audit trail your security team can trust.</p><div className="hero-actions"><button className="primary-btn" onClick={onAdd}>Start offboarding</button><button className="secondary-btn" onClick={onActivity}>View agent activity <b>→</b></button></div></div><div className="agent-visual"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="agent-core"><strong>AI</strong><small>AGENT</small></div></div></section><section className="stats-grid"><Stat label="ACTIVE CASES" value={activeCases} detail="Currently processing" /><Stat label="COMPLETED" value={completedCases} detail="Audit reports ready" /><Stat label="SYSTEMS MONITORED" value="06" detail="Simulated adapters" /><Stat label="EXCEPTIONS" value={exceptions} detail="Needs attention" warning /></section><section className="content-grid"><div className="panel"><PanelHeader title="Offboarding workflow" subtitle="One exit event to verified evidence" /><div className="workflow">{FLOW.map((step, index) => <div className="workflow-item" key={step}><div className={`workflow-circle ${index < 4 ? "done" : ""}`}>{index < 4 ? "✓" : index + 1}</div><div><strong>{step}</strong><span>{["HR exit event received", "Scanning connected systems", "Revoking active sessions", "Validating access removal", "Handling unresolved access", "Generating evidence"][index]}</span></div>{index < FLOW.length - 1 && <div className="workflow-line" />}</div>)}</div></div><div className="panel"><PanelHeader title="Recent employees" subtitle="HR-submitted offboarding cases" />{employees.slice(0, 5).map((employee) => <EmployeeRow key={employee.id} employee={employee} onStart={() => onStart(employee)} />)}{!employees.length && <EmptyState onClick={onAdd} />}</div></section><div className="exception-banner"><div className="exception-icon">!</div><div><strong>Known demo exception: AWS</strong><p>AWS deliberately stays active after revocation so the agent can retry, escalate and preserve evidence of the failure.</p></div><b className="critical-tag">CRITICAL</b></div></> }

function Employees({ employees, onAdd, onStart }) { return <section className="page-section"><PageTitle title="Employee directory" subtitle="Create and run a controlled offboarding case." /><div className="section-toolbar"><span>{employees.length} employee{employees.length === 1 ? "" : "s"} in local JSON store</span><button className="primary-btn" onClick={onAdd}>+ Add employee</button></div><div className="employee-cards">{employees.map((employee) => <div className="employee-card" key={employee.id}><Avatar name={employee.name} /><div className="employee-main"><h3>{employee.name}</h3><p>{employee.id} · {employee.email}</p><div className="employee-details"><span>{employee.role}</span><span>{employee.department}</span><span>Exit {employee.exitDate}</span></div></div><div className="employee-right"><Status status={employee.status} /><button className="small-action" onClick={() => onStart(employee)}>{employee.status === "Completed" ? "Run again" : "Start →"}</button></div></div>)}</div>{!employees.length && <EmptyState onClick={onAdd} />}</section> }

function Activity({ activities }) { const latest = activities; return <section className="page-section"><PageTitle title="Agent activity" subtitle="Every decision and tool action is recorded locally." /><div className="activity-layout"><div className="panel"><PanelHeader title="Live telemetry" subtitle={`${latest.length} events retained in JSON audit log`} />{latest.map((item) => <div className="activity-row" key={item.id}><div className={`activity-bullet ${item.type === "ESCALATE" ? "danger" : ""}`} /><div className="activity-content"><span>{item.type}</span><strong>{item.text}</strong></div><time>{item.time}</time></div>)}</div><div className="agent-card"><div className="agent-card-icon">AI</div><span className="online-label">● ONLINE</span><h2>Offboarding agent</h2><p>Controlled orchestration with post-action verification.</p><Metric name="Decision engine" value="READY" /><Metric name="Tool access" value="CONTROLLED" /><Metric name="Audit logging" value={`${latest.length} EVENTS`} /></div></div></section> }

function AccessControl({ onAdd }) { const [checked, setChecked] = useState({}); return <section className="page-section"><PageTitle title="Access control" subtitle="Connected adapters available to the orchestration engine." /><div className="systems-grid">{SYSTEMS.map((system) => <div className="system-card" key={system.name}><div className="system-logo">{system.short}</div><div className="system-info"><h3>{system.name}</h3><p>{system.type} · {system.role}</p></div><div className="connected"><span /> CONNECTED</div><div className="system-actions"><button onClick={() => setChecked({ ...checked, [system.name]: checked[system.name] === "Active" ? "Revoked" : "Active" })}>{checked[system.name] ? `Status: ${checked[system.name]}` : "Get access status"}</button><button onClick={() => setChecked({ ...checked, [system.name]: "Revoked" })}>Revoke access</button></div></div>)}</div><div className="info-callout"><strong>Simulated adapter mode</strong><span>Each adapter exposes discovery, revoke and verify actions. AWS is configured as the deliberate verification failure for the demo.</span><button className="secondary-btn" onClick={onAdd}>Run with an employee →</button></div></section> }

function Reports({ reports }) { const report = reports[0]; return <section className="page-section"><PageTitle title="Audit reports" subtitle="Evidence generated after an offboarding workflow completes." />{!report ? <EmptyState text="Complete an offboarding workflow to generate an audit report." /> : <div className="report-layout"><div className="panel report-panel"><div className="report-header"><div><span className="eyebrow">AUDIT RECORD · {report.id}</span><h2>{report.employee.name}</h2><p>{report.employee.department} · Exit {report.employee.exitDate}</p></div><button className="secondary-btn" onClick={() => window.print()}>Print / save PDF</button></div><div className="report-stats"><Stat label="SYSTEMS CHECKED" value={report.systemsChecked} detail="All adapters queried" /><Stat label="REVOKED" value={report.revoked} detail="Verification passed" /><Stat label="ESCALATED" value={report.escalated} detail="Manual action required" warning /></div><div className="report-table">{report.employee.systems.map((system) => <div className="report-row" key={system.name}><span><strong>{system.name}</strong><small>{system.role}</small></span><Status status={system.status === "Escalated" ? "Escalated" : "Revoked"} /></div>)}</div></div><div className="critical-report"><div className="critical-report-icon">!</div><span>CRITICAL EXCEPTION</span><h3>AWS access still active</h3><p>Revocation was requested, but verification found the IAM user active after two attempts. IT Security must manually revoke access.</p><div className="retry-box"><span>Attempts</span><strong>02</strong></div><div className="retry-box"><span>Risk</span><strong>CRITICAL</strong></div></div></div>}</section> }

function HowItWorks() { return <section className="page-section how-page"><PageTitle title="How it works" subtitle="A clear operator guide from HR exit event to audit-ready evidence." /><div className="how-intro"><div><span className="eyebrow">START HERE</span><h2>One exit event. Six controlled checks.</h2><p>Use this sequence when you demo or operate OffboardAI. Every step is visible in the activity log and stored with the employee case.</p></div><div className="how-contract"><span>INPUT</span><strong>Employee exit event</strong><small>HR submits name, ID, email, role, department and exit date.</small></div></div><div className="how-steps">{[["01", "Start with Employees", "Add or select the departing employee. Check the exit date and identity details before starting.", "Where to check: Employees page"], ["02", "Trigger the exit", "Click Start on the employee case. The agent marks the case In Progress and records the HR event.", "Where to check: Workflow modal"], ["03", "Discover access", "The agent queries all six simulated adapters and normalizes each system, role and current status.", "Where to check: Access Control + modal"], ["04", "Revoke access", "Revocation tasks run for Slack, GitHub, AWS, Salesforce, Figma and Jira. Each action is tracked.", "Where to check: Agent Activity"], ["05", "Verify removal", "The agent checks the systems again. Five systems pass. AWS intentionally remains active after the request.", "Where to check: Workflow warning + report"], ["06", "Escalate and report", "AWS is retried, escalated to IT Security, and the completed evidence is saved as an audit report.", "Where to check: Audit Reports"]].map(([number, title, text, check]) => <article className="how-step" key={number}><div className="how-number">{number}</div><div><h3>{title}</h3><p>{text}</p><span>{check}</span></div></article>)}</div><div className="how-result"><div><span className="eyebrow">EXPECTED RESULT</span><h2>5 revoked · 1 escalated · 1 audit report</h2><p>The exception is intentional for the MVP. In production, replace the mock adapters with live admin APIs while keeping the same orchestration and verification contract.</p></div><div className="result-path"><b>HR</b><span>→</span><b>AGENT</b><span>→</span><b>VERIFY</b><span>→</span><b>AUDIT</b></div></div></section> }

function WorkflowModal({ employee, phase, onClose, onOpenReport }) { const done = phase >= 5; return <div className="modal-backdrop"><div className="simulation-modal"><div className="simulation-top"><div><span className="eyebrow">AUTONOMOUS WORKFLOW</span><h2>{employee.name}</h2><p>{done ? "Workflow complete. One exception requires manual action." : "Agent is executing controlled de-provisioning."}</p></div><button className="close-btn" onClick={onClose}>×</button></div><div className="simulation-flow">{FLOW.map((item, index) => { const complete = index < phase || (done && index === phase); return <div className={`simulation-step ${complete ? "complete" : index === phase ? "current" : ""}`} key={item}><div className="simulation-number">{complete ? "✓" : index + 1}</div><div><strong>{item}</strong><span>{complete ? "Completed" : index === phase ? "Processing..." : "Waiting"}</span></div></div>; })}</div>{phase >= 3 && <div className="simulation-warning"><div>!</div><p><strong>AWS verification failed.</strong><br />Access remains ACTIVE. The agent retries, then escalates to IT Security.</p></div>}{done ? <button className="primary-btn full-btn" onClick={onOpenReport}>Open audit report</button> : <div className="processing"><span className="loader" /> Agent processing workflow...</div>}</div></div> }

function AddModal({ form, setForm, onClose, onSubmit }) { return <div className="modal-backdrop"><div className="modal"><div className="modal-header"><div><span className="eyebrow">HR ACTION</span><h2>Add employee</h2><p>Create a new local offboarding case.</p></div><button className="close-btn" onClick={onClose}>×</button></div><form onSubmit={onSubmit}><div className="form-grid">{[["name", "Employee name", "Full name"], ["employeeId", "Employee ID", "EMP-002"], ["email", "Work email", "employee@company.com"], ["role", "Role", "Software Engineer"], ["department", "Department", "Engineering"]].map(([key, label, placeholder]) => <label className="input-group" key={key}><span>{label}</span><input required type={key === "email" ? "email" : "text"} value={form[key]} placeholder={placeholder} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /></label>)}<label className="input-group"><span>Exit date</span><input required type="date" value={form.exitDate} onChange={(event) => setForm({ ...form, exitDate: event.target.value })} /></label></div><div className="modal-actions"><button type="button" className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn">Create case</button></div></form></div></div> }

function Stat({ label, value, detail, warning }) { return <div className={`stat-card ${warning ? "warning-card" : ""}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></div> }
function Metric({ name, value }) { return <div className="agent-metric"><span>{name}</span><strong>{value}</strong></div> }
function PanelHeader({ title, subtitle }) { return <div className="panel-header"><div><h2>{title}</h2><p>{subtitle}</p></div></div> }
function PageTitle({ title, subtitle }) { return <div className="page-title"><span className="eyebrow">OFFBOARDING CONTROL</span><h1>{title}</h1><p>{subtitle}</p></div> }
function Avatar({ name }) { return <div className="employee-avatar">{name.charAt(0).toUpperCase()}</div> }
function EmployeeRow({ employee, onStart }) { return <div className="employee-row"><Avatar name={employee.name} /><div className="employee-row-info"><strong>{employee.name}</strong><span>{employee.id} · {employee.department}</span></div><Status status={employee.status} /><button className="small-action" onClick={onStart}>{employee.status === "Pending" ? "Start" : "View"}</button></div> }
function Status({ status }) { const normalized = status.toLowerCase().replaceAll(" ", "-"); return <span className={`status status-${normalized}`}><span />{status}</span> }
function EmptyState({ onClick, text = "Add an employee to begin an offboarding workflow." }) { return <div className="large-empty"><div className="empty-icon">+</div><h3>No cases to show</h3><p>{text}</p>{onClick && <button className="primary-btn" onClick={onClick}>Add employee</button>}</div> }

export default App;
